### ISSUE TITLE
Error: "zipfile.BadZipFile: File is not a zip file"

### ISSUE THREAD

**Issue by thomas-chia** [Qengineering/TensorFlow-Addons-Jetson-Nano#1]
Hello, I am trying to install the tfa for Jetson using your .whl, however it seems as if the wheel file is corrupted/damaged/unusable.

When installing using this command:
`sudo pip3 install tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl`

I am getting this error: 

ideaking001@ideaking001-desktop:~$ sudo pip3 install tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl
Processing ./tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 317, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 101, in resolve
    req, requested_extras=(),
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 306, in make_requirement_from_install_req
    version=None,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 169, in _make_candidate_from_link
    name=name, version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    version=version,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 312, in _prepare_distribution
    self._ireq, parallel_builds=True,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 457, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 501, in _prepare_linked_requirement
    req, self.req_tracker, self.finder, self.build_isolation,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 67, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/distributions/wheel.py", line 30, in get_pkg_resources_distribution
    with ZipFile(self.req.local_file_path, allowZip64=True) as z:
  File "/usr/lib/python3.6/zipfile.py", line 1131, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Is it possible for you to reupload a working .whl for tfa on Jetson? Thank you for your help in advance.

**Comment by Qengineering** [comment]
Thanks for letting me know!

A typo. Please use: 
```
$ wget https://github.com/Qengineering/TensorFlow-Addons-Jetson-Nano/raw/main/tensorflow_addons-0.13.0.dev0-cp36-cp36m-linux_aarch64.whl
```
(I had `.../blob/main..` while it should be `.../raw/main...`) 

Kind regards.

**Comment by thomas-chia** [comment]
@Qengineering Thanks! It works now. Its much easier than to rebuild. 

Side note, do you have a tutorial for installing tf-object detection 2 on Jetson Nano?

**Comment by Qengineering** [comment]
With TF installed on your Nano, it's almost as if you have TF running on Ubuntu with a (small) GPU on a PC. Lots of articles on the net. Google is your friend here. That's why I don't have written a tutorial.
